services:
  - type: web
    name: auto-absen-simkuliah
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app --bind 0.0.0.0:$PORT --threads 4
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
